import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const helvetica_neue = localFont({
    src: '../../public/font/HelveticaNeue-Roman.otf',
    variable: '--font-helvetica_neue',
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={`${helvetica_neue.className} ${inter.className}`}>
                {children}
            </body>
        </html>
    );
}
